### ISSUE TITLE
Soundcloud embeds do not work.

### ISSUE THREAD

**Issue by hizzvizz** [steemit/steemit.com#170]
Expectation: I have posted on steemit.com and used youtube embeds in this post. The work in the preview and the video plays fine on desktop and mobile browsers.

Result: Here is an embed code I've tried to use from soundcloud.

<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/278598634&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>

This either shows nothing, or shows a message saying soundcloud embeds aren't supported.

**Comment by roadscape** [comment]
Could you please provide a link to the post which exhibits this behavior?

**Comment by mcifani** [comment]
Soundcloud embeds should be working fine.  Make sure to insert the entire code after you click the embed tab/insert and you'll see the player in the post preview.

**Comment by hizzvizz** [comment]
I have verified this is working now. The vimeo bug is still valid ([#171](https://github.com/steemit/steemit.com/issues/171)).

**Comment by hizzvizz** [comment]
Ok. It works on desktop browsers, but on my iPhone in Safari or Chrome, I can't see the embed.

Here is a [post](https://steemit.com/music/@rubenalexander/the-connection-between-math-and-music-part-2-video-of-my-new-song-called-steem-life-free-download) with a soundcloud embed.

**Comment by jcalfee** [comment]
Here is the embedded iframe from the post.  It matches the embedded code from the original clip.  The bug lies between the phone and sound-cloud.  There are other issues posted on the Internet involving sound-cloud and phones.  I hope it will be resolved soon.  I imagine they are aware of the issue.  When resolved no action from steemit will be needed.

`<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/279649435&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>`

This is an interesting post.. thank you..
